services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uv run fastapi dev src/job_market_intel/main.py --host 0.0.0.0
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/job_market_intel
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - db
      - redis
    
  worker:
    build: .
    volumes:
      - .:/app
    command: uv run celery -A job_market_intel.worker:celery_app worker --loglevel=info
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/job_market_intel
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      - db
      - redis

  redis:
    image: redis:7

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: job_market_intel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: