"""add posting identify fields

Revision ID: 20535cb5538c
Revises: b17cb44f5b6d
Create Date: 2026-07-14 15:58:14.334357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20535cb5538c'
down_revision: Union[str, Sequence[str], None] = 'b17cb44f5b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('job', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('job', sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('job', sa.Column('fingerprint', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.create_index(op.f('ix_job_fingerprint'), 'job', ['fingerprint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_fingerprint'), table_name='job')
    op.drop_column('job', 'fingerprint')
    op.drop_column('job', 'source_url')
    op.drop_column('job', 'external_id')
    op.drop_column('job', 'source')
    # ### end Alembic commands ###
