"""add created_at and updated_at to job

Revision ID: 8cecf8b6d6f5
Revises: 5a87764e252d
Create Date: 2026-07-09 15:22:37.866922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8cecf8b6d6f5'
down_revision: Union[str, Sequence[str], None] = '5a87764e252d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('job', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'updated_at')
    op.drop_column('job', 'created_at')
    # ### end Alembic commands ###
